from .staff_required import staff_required
from .merchant_dashboard import merchant_dashboard
from .sales_report import sales_report
from .customer_list import customer_list
from .staff_user_list import staff_user_list
from .order_list import order_list
from .order_detail import order_detail
from .merchant_product_list import merchant_product_list
from .add_product import add_product
from .edit_product import edit_product
from .delete_product import delete_product
from .import_product_from_url import import_product_from_url
from .download_template import download_template
from .import_excel import import_excel
from .edit_product import edit_product
from .promotions_list import promotions_list
from .loyalty_program import loyalty_program
from .banners_list import banners_list
from .affiliate_marketing import affiliate_marketing