from .merchant.staff_required import staff_required
from .public.home import home
from .public.product_list import product_list
from .public.product_detail import product_detail
from .public.live_search import live_search
from .cart.add_to_cart import add_to_cart
from .cart.cart_detail import cart_detail
from .cart.remove_from_cart import remove_from_cart
from .cart.update_cart_quantity import update_cart_quantity
from .orders.checkout import checkout
from .account.register_user import register_user
from .account.login_user import login_user
from .account.logout_user import logout_user
from .account.customer_profile import customer_profile
from .merchant.merchant_dashboard import merchant_dashboard
from .merchant.sales_report import sales_report
from .merchant.customer_list import customer_list
from .merchant.staff_user_list import staff_user_list
from .merchant.order_list import order_list
from .merchant.order_detail import order_detail
from .merchant.merchant_product_list import merchant_product_list
from .merchant.add_product import add_product
from .merchant.edit_product import edit_product
from .merchant.delete_product import delete_product
from .merchant.import_product_from_url import import_product_from_url
from .merchant.download_template import download_template
from .merchant.import_excel import import_excel
from .public.review_views import add_review