# Generated by Django 6.1.1 on 2026-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة المفضلة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(default='العربية', max_length=10, verbose_name='لغة الحساب'),
        ),
    ]
