# Generated by Django 6.1.1 on 2026-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_currency_customer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=123456789, max_length=20, unique=True, verbose_name='الهاتف'),
            preserve_default=False,
        ),
    ]
