# Generated by Django 6.1.1 on 2026-09-25 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الخصم')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية (%)'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('active', models.BooleanField(default=True, verbose_name='نشط / مفعل')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='صالح من تاريخ')),
                ('valid_to', models.DateTimeField(verbose_name='صالح حتى تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'الكوبونات والعروض التسويقية',
            },
        ),
    ]
