# Generated by Django 6.1.1 on 2026-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('payment_type', models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي'), ('mobile_wallet', 'محفظة إلكترونية'), ('card', 'بطاقة ائتمان'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='نوع طريقة الدفع')),
                ('instructions', models.TextField(blank=True, help_text='مثال: رقم الحساب البنكي، اسم المستفيد، أو أي تفاصيل يحتاجها العميل', verbose_name='تعليمات الدفع (تظهر للعميل)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الشحن')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم شركة التوصيل')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='مدة التوصيل المتوقعة (أيام)')),
                ('covered_cities', models.TextField(blank=True, help_text='افصل بين أسماء المدن بفاصلة، مثال: صنعاء، عدن، تعز', verbose_name='المدن المشمولة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'طريقة شحن',
                'verbose_name_plural': 'طرق الشحن',
                'ordering': ['cost'],
            },
        ),
    ]
