# Generated by Django 6.1.1 on 2026-09-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='المواصفات الفنية'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='يمكنك رفع فيديو للمنتج (MP4)', null=True, upload_to='products/videos/', verbose_name='فيديو المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='الصورة الإضافية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': 'معرض صور المنتجات',
            },
        ),
    ]
