# Generated by Django 6.1.1 on 2026-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_paymentmethod_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='اختياري - يُستخدم لمقارنة الوزن الحجمي بالوزن الفعلي', max_digits=6, verbose_name='الوزن الفعلي (كغم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='العرض (سم)'),
        ),
    ]
