# Generated by Django 6.1.1 on 2026-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_cm',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='min_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى لتكلفة الشحن'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='price_per_cbm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشحن لكل متر مكعب (CBM)'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='رسوم تُضاف دائمًا فوق تكلفة الحجم (اتركها 0 إن لم ترغب برسوم ثابتة)', max_digits=10, verbose_name='رسوم ثابتة إضافية'),
        ),
    ]
