# Generated by Django 6.1.1 on 2026-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='الطول (سم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='اختياري - لوزن الأشياء الخفيفة استخدم كسورًا عشرية، مثال: 0.050 = 50 غرام', max_digits=6, verbose_name='الوزن الفعلي (كغم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='العرض (سم)'),
        ),
    ]
