# Generated by Django 6.1.1 on 2026-09-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_carton_height_cm_product_carton_length_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carton_height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carton_length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carton_weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carton_width_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units_per_carton',
        ),
    ]
