# Generated by Django 6.1.1 on 2026-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_carton_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carton_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='ارتفاع الكرتون (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='طول الكرتون (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='اختياري - الوزن الكلي للكرتون بكل قطعه', max_digits=6, verbose_name='وزن الكرتون الفعلي (كغم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carton_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='عرض الكرتون (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_carton',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='عدد القطع في الكرتون الواحد'),
        ),
    ]
