# Generated by Django 6.1.1 on 2026-09-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_carton_height_cm_product_carton_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('regular', 'عادي'), ('wholesale', 'جملة'), ('vip', 'مميز')], default='regular', max_length=20, verbose_name='تصنيف العميل'),
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('read', 'مقروءة'), ('replied', 'تم الرد')], default='new', max_length=10, verbose_name='الحالة')),
                ('reply_text', models.TextField(blank=True, verbose_name='نص الرد')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='shop.customer', verbose_name='العميل (إن كان مسجلاً)')),
            ],
            options={
                'verbose_name': 'رسالة عميل',
                'verbose_name_plural': 'رسائل العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
