# Generated by Django 6.1.1 on 2026-09-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_customer_customer_type_customermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='اسم مقدم الطلب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج المطلوب')),
                ('specifications', models.TextField(blank=True, verbose_name='مواصفات المنتج')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('approximate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر التقريبي (إن وجد)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewing', 'قيد المراجعة'), ('available', 'تم التوفير'), ('rejected', 'غير متاح')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests', to='shop.customer', verbose_name='العميل (إن كان مسجلاً)')),
            ],
            options={
                'verbose_name': 'طلب منتج غير متوفر',
                'verbose_name_plural': 'طلبات المنتجات غير المتوفرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_requests/', verbose_name='صورة')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productrequest', verbose_name='الطلب')),
            ],
        ),
    ]
