# Generated by Django 6.1.1 on 2026-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productrequest_productrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط يوتيوب أو تيك توك أو أي منصة أخرى يوضح المنتج المطلوب', null=True, verbose_name='رابط فيديو للمنتج (اختياري)'),
        ),
    ]
