# Generated by Django 6.1.1 on 2026-10-01 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_payment_method_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6, verbose_name='نسبة الربح - تجزئة (%)')),
                ('wholesale_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6, verbose_name='نسبة الربح - جملة (%)')),
                ('super_wholesale_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, verbose_name='نسبة الربح - جملة الجملة (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات التسعير',
                'verbose_name_plural': 'إعدادات التسعير',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الماركة'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر التكلفة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('regular', 'عادي'), ('wholesale', 'جملة'), ('super_wholesale', 'جملة الجملة'), ('vip', 'مميز')], default='regular', max_length=20, verbose_name='تصنيف العميل'),
        ),
    ]
