# Generated by Django 6.1.1 on 2026-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_pricingsettings_remove_product_price_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة التصنيف'),
        ),
    ]
