# Generated by Django 6.1.1 on 2026-10-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier_store_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='رقم متجر المورد'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_store_number',
            field=models.CharField(blank=True, default='', help_text='اختياري - يظهر لك فقط في تفاصيل الطلب والطباعة ولا يراه العميل', max_length=100, verbose_name='رقم متجر المورد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='الرابط (Slug)'),
        ),
    ]
